export const TABs = {
  HOME: 'HOME',
  DISCOVER: 'DISCOVER',
  AI: 'AI',
  AICHAT: 'AICHAT',
  WORKSHOP: 'WORKSHOP',
  WORKSHOP_IDLE: 'WORKSHOP_IDLE',
  PROFILE: 'PROFILE',
  HAND_DESIGN: 'HAND_DESIGN',
  NAIL_DESIGN: 'NAIL_DESIGN',
  PRODUCT: 'PRODUCT',
  DESIGN_PREVIEW: 'DESIGN_PREVIEW',
  SHARE_DESIGN: 'SHARE_DESIGN',
  LOAD: 'Load',
  THEME: 'THEME',
  COLLECTION: 'COLLECTION',
  CART: 'CART',
  SEARCH: 'SEARCH',
  SETTINGS: 'SETTINGS',
  ADDRESS: 'ADDRESS',
  NAME: 'NAME',
  PAYMENT: 'PAYMENT',
  CONFIRMATION: 'CONFIRMATION',
};

export const TAB_TITLES = {
  [TABs.HOME]: 'Welcome, {NAME}',
  [TABs.DISCOVER]: 'Discover',
  [TABs.PROFILE]: 'Me',
  [TABs.WORKSHOP]: 'Select Your Single Nails',
  [TABs.WORKSHOP_IDLE]: 'Start Design Your Nails',
  [TABs.HAND_DESIGN]: 'Design My Nails',
  [TABs.NAIL_DESIGN]: 'Hand',
  [TABs.DESIGN_PREVIEW]: 'Design Preview',
  [TABs.SHARE_DESIGN]: 'Share your design',
  [TABs.LOAD]: 'Loading',
  [TABs.THEME]: 'Theme',
  [TABs.COLLECTION]: 'Collection',
  [TABs.CART]: 'Shopping Bag',
  [TABs.SETTINGS]: 'Settings',
  [TABs.ADDRESS]: 'Address',
  [TABs.NAME]: 'My Name',
  [TABs.PAYMENT]: 'Payment',
  [TABs.CONFIRMATION]: 'Order Confirmation',
};
